---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    provider: lxc
    box: ubuntu-12.04-amd64-vbox
    box_url: https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-12.04-amd64-vbox.box

suites:
- name: default
  run_list: 
    - "recipe[trema::default]"
  attributes:
