---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    provider: lxc
    box: precise-server-cloudimg-i386-vagrant-disk1
    box_url: https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-i386-vagrant-disk1.box

suites:
- name: default
  run_list: 
    - "recipe[trema::default]"
  attributes:
