---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: Centos-LXC-6.5
  driver_config:
    provider: lxc
    box: vagrant-lxc-Centos-6.5-x86_64-ja
    box_url: https://dl.dropboxusercontent.com/u/428597/vagrant_boxes/vagrant-lxc-Centos-6.5-x86_64-ja.box

suites:
- name: default
  run_list: 
    - "recipe[trema::default]"
  attributes:
